import DashboardLayout from "@/components/DashboardLayout";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CalendarClock, CheckCircle2, Clock3, Loader2, Mail, PlayCircle, Send, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const days = ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"];
const formatDate = (value: Date | string | null | undefined) => value ? new Date(value).toLocaleString("fr-FR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }) : "À définir";
const campaignStatus = (status: string) => ({ active_simulation: ["Simulation active", "border-emerald-200 bg-emerald-50 text-emerald-800"], approuvee: ["Prête à activer", "border-blue-200 bg-blue-50 text-blue-800"], a_approuver: ["À approuver", "border-amber-200 bg-amber-50 text-amber-800"], simulee: ["Brouillon simulé", "border-slate-200 bg-slate-50 text-slate-700"], suspendue: ["Suspendue", "border-rose-200 bg-rose-50 text-rose-800"] } as Record<string, string[]>)[status] ?? [status, "border-slate-200 bg-slate-50 text-slate-700"];

export default function AgentCampaignSchedulerPage() {
  const utils = trpc.useUtils();
  const { data: center, isLoading, error } = trpc.billing.agent.center.useQuery();
  const [scheduleCampaign, setScheduleCampaign] = useState<any | null>(null);
  const invalidate = () => utils.billing.agent.center.invalidate();
  const saveSchedule = trpc.billing.agent.scheduleCampaign.useMutation({ onSuccess: () => { invalidate(); setScheduleCampaign(null); toast.success("Programmation enregistrée. Elle exécutera uniquement la boîte e-mail de test interne."); }, onError: error => toast.error(error.message) });
  const runTest = trpc.billing.agent.runTestEmailNow.useMutation({ onSuccess: result => { invalidate(); toast.success(result.status === "success" ? `${result.delivered} message(s) remis dans la boîte de test.` : result.reason ?? "Aucun brouillon de test n’est disponible."); }, onError: error => toast.error(error.message) });
  const scheduled = useMemo(() => center?.campaigns.filter((campaign: any) => campaign.scheduleCronTaskUid) ?? [], [center?.campaigns]);
  const eligible = useMemo(() => center?.campaigns.filter((campaign: any) => campaign.status === "active_simulation" && campaign.channel === "email") ?? [], [center?.campaigns]);
  if (isLoading) return <DashboardLayout><div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div></DashboardLayout>;
  if (error) return <DashboardLayout><div className="mx-auto max-w-3xl py-10"><Alert variant="destructive"><AlertTriangle className="h-4 w-4" /><AlertTitle>Accès réservé</AlertTitle><AlertDescription>{error.message}</AlertDescription></Alert></div></DashboardLayout>;
  return <DashboardLayout><main className="mx-auto max-w-6xl pb-10"><header className="border-b border-border pb-6"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-primary">Agent IA · Administration</p><h1 className="font-editorial mt-2 text-3xl font-semibold">Planificateur de campagnes</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Programmez visuellement les simulations e-mail approuvées. Le calendrier est exprimé à l’heure de Conakry et reste relié à une campagne précise.</p></header>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><Metric icon={CalendarClock} value={scheduled.length} label="Programmations actives" /><Metric icon={Clock3} value={eligible.length} label="Campagnes prêtes" /><Metric icon={Mail} value={center?.summary.testDelivered ?? 0} label="E-mails remis en test" /></section>
    <section className="mt-6 rounded-2xl border border-primary/15 bg-primary/[0.035] p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><div><h2 className="text-sm font-extrabold">Calendrier durable, canal isolé</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Une tâche planifiée réveille l’application à l’heure choisie et copie les brouillons dans la boîte e-mail interne de test. Elle ne contacte ni une boîte personnelle, ni Gmail, ni WhatsApp.</p></div></div></section>
    <section className="mt-8"><Heading title="Échéancier de la semaine" detail="Les prochaines exécutions sont mises à jour dès qu’une programmation est validée." /><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{scheduled.length ? scheduled.map((campaign: any) => <ScheduleCard key={campaign.id} campaign={campaign} onTest={() => runTest.mutate({ campaignId: campaign.id })} pending={runTest.isPending} />) : <Empty text="Aucune campagne n’est programmée. Activez d’abord une campagne e-mail en simulation depuis le Centre de délégations." />}</div></section>
    <section className="mt-8"><Heading title="Campagnes à programmer" detail="Seules les campagnes e-mail actives en simulation peuvent être planifiées pour la boîte de test." /><div className="mt-4 overflow-hidden rounded-2xl border border-border bg-card"><div className="hidden grid-cols-[1.3fr_0.8fr_0.7fr_0.9fr] gap-4 border-b border-border bg-secondary/60 px-5 py-3 text-[11px] font-extrabold uppercase tracking-[0.12em] text-muted-foreground md:grid"><span>Campagne</span><span>Audience</span><span>Statut</span><span className="text-right">Action</span></div>{eligible.length ? eligible.map((campaign: any) => { const [label, color] = campaignStatus(campaign.status); return <div key={campaign.id} className="grid gap-3 border-b border-border p-4 last:border-0 md:grid-cols-[1.3fr_0.8fr_0.7fr_0.9fr] md:items-center md:px-5"><div><p className="text-sm font-extrabold">{campaign.name}</p><p className="mt-1 text-xs text-muted-foreground">{campaign.delegationName} · {campaign.purpose === "relance_facture" ? "Relance facture" : "Suivi devis"}</p></div><p className="text-xs font-bold">{campaign.eligibleCount} brouillon(s)</p><Badge variant="outline" className={`w-fit ${color}`}>{label}</Badge><div className="flex flex-wrap justify-start gap-2 md:justify-end">{campaign.scheduleCronTaskUid ? <Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-800">Déjà programmé</Badge> : <Button size="sm" className="rounded-lg bg-primary text-primary-foreground" onClick={() => setScheduleCampaign(campaign)}><CalendarClock className="mr-1.5 h-3.5 w-3.5" />Programmer</Button>}<Button size="sm" variant="outline" className="rounded-lg border-primary/20 text-primary" disabled={runTest.isPending} onClick={() => runTest.mutate({ campaignId: campaign.id })}><Send className="mr-1.5 h-3.5 w-3.5" />Tester</Button></div></div>; }) : <Empty text="Aucune campagne e-mail active n’est prête. Créez, approuvez et activez une simulation dans le Centre de délégations." />}</div></section>
  </main><ScheduleDialog campaign={scheduleCampaign} onOpenChange={(open: boolean) => !open && setScheduleCampaign(null)} pending={saveSchedule.isPending} onSave={(input: any) => saveSchedule.mutate(input)} /></DashboardLayout>;
}
function Metric({ icon: Icon, value, label }: any) { return <div className="rounded-2xl border border-border bg-card p-4"><Icon className="h-5 w-5 text-primary" /><p className="font-editorial mt-5 text-3xl font-semibold">{value}</p><p className="mt-1 text-xs font-bold text-muted-foreground">{label}</p></div>; }
function Heading({ title, detail }: { title: string; detail: string }) { return <div><h2 className="font-editorial text-2xl font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{detail}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="col-span-full p-8 text-center text-xs leading-5 text-muted-foreground">{text}</div>; }
function ScheduleCard({ campaign, onTest, pending }: any) { return <article className="card-shadow rounded-2xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-extrabold">{campaign.name}</p><p className="mt-1 text-xs text-muted-foreground">{campaign.eligibleCount} brouillon(s) · e-mail de test</p></div><Badge variant="outline" className="border-emerald-200 bg-emerald-50 text-emerald-800">Programmé</Badge></div><div className="mt-4 space-y-2 rounded-xl bg-secondary/60 p-3 text-xs"><p className="flex justify-between gap-3"><span className="text-muted-foreground">Rythme</span><strong>{campaign.scheduleCronExpression || "—"}</strong></p><p className="flex justify-between gap-3"><span className="text-muted-foreground">Prochaine exécution</span><strong className="text-right">{formatDate(campaign.nextExecutionAt)}</strong></p><p className="flex justify-between gap-3"><span className="text-muted-foreground">Dernier statut</span><strong>{campaign.lastExecutionStatus}</strong></p></div><Button size="sm" variant="outline" className="mt-4 w-full rounded-lg border-primary/20 text-primary" disabled={pending} onClick={onTest}><PlayCircle className="mr-1.5 h-3.5 w-3.5" />Exécuter un test maintenant</Button></article>; }
function ScheduleDialog({ campaign, onOpenChange, onSave, pending }: any) { const [frequency, setFrequency] = useState("daily"); const [time, setTime] = useState("09:00"); const [weekday, setWeekday] = useState("1"); return <Dialog open={Boolean(campaign)} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Programmer une campagne</DialogTitle><DialogDescription>La programmation ne délivre les messages qu’à la boîte de test interne. Le fuseau est fixé sur Conakry.</DialogDescription></DialogHeader>{campaign && <div className="grid gap-4 py-3"><div className="rounded-xl bg-secondary/60 p-3 text-xs"><strong className="block">{campaign.name}</strong><span className="mt-1 block text-muted-foreground">{campaign.eligibleCount} brouillon(s) · e-mail de test</span></div><label className="grid gap-1.5 text-xs font-extrabold">Fréquence<select className="h-10 rounded-xl border border-border bg-background px-3 text-sm" value={frequency} onChange={event => setFrequency(event.target.value)}><option value="daily">Chaque jour</option><option value="weekly">Chaque semaine</option></select></label>{frequency === "weekly" && <label className="grid gap-1.5 text-xs font-extrabold">Jour<select className="h-10 rounded-xl border border-border bg-background px-3 text-sm" value={weekday} onChange={event => setWeekday(event.target.value)}>{days.map((day, index) => <option key={day} value={index}>{day}</option>)}</select></label>}<label className="grid gap-1.5 text-xs font-extrabold">Heure (Conakry)<input className="h-10 rounded-xl border border-border bg-background px-3 text-sm" type="time" value={time} onChange={event => setTime(event.target.value)} /></label><p className="flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-[11px] leading-4 text-amber-950"><AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" />Une campagne est programmée après publication. Vous pourrez la suspendre à tout moment depuis le Centre de délégations.</p><Button className="w-full rounded-xl bg-primary font-bold text-primary-foreground" disabled={pending} onClick={() => onSave({ campaignId: campaign.id, frequency, time, weekday: frequency === "weekly" ? Number(weekday) : undefined })}>{pending ? "Programmation…" : "Enregistrer le calendrier"}</Button></div>}</DialogContent></Dialog>; }
