import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { formatGnf } from "@shared/billing";
import { LUCEPRES_PUBLIC_PROFILE } from "@shared/companyProfile";
import { selectDashboardDocuments } from "@shared/dashboardFilters";
import { AlertTriangle, ArrowUpRight, BarChart3, Bot, CalendarDays, CircleDollarSign, FilePlus2, ReceiptText, Send, Sparkles, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

type QuickFilter = "all" | "overdue" | "pending_quotes";

export default function Home() {
  const [, setLocation] = useLocation();
  const [quickFilter, setQuickFilter] = useState<QuickFilter>("all");
  const { data: dashboard, isLoading } = trpc.billing.dashboard.useQuery(undefined, { refetchInterval: 15_000 });
  const { data: documents = [] } = trpc.billing.documents.list.useQuery(undefined, { refetchInterval: 15_000 });
  const { data: receivables } = trpc.billing.receivables.useQuery(undefined, { refetchInterval: 15_000 });
  const { data: profitability = [] } = trpc.billing.projects.costs.profitability.useQuery(undefined, { refetchInterval: 15_000 });
  const overdueInvoices = useMemo(() => selectDashboardDocuments(documents, "overdue"), [documents]);
  const pendingQuotes = useMemo(() => selectDashboardDocuments(documents, "pending_quotes"), [documents]);
  const totalMargin = useMemo(() => profitability.reduce((sum, project) => sum + project.margin, 0), [profitability]);
  const visibleDocuments = quickFilter === "overdue" ? overdueInvoices : quickFilter === "pending_quotes" ? pendingQuotes : dashboard?.priority ?? [];
  const filterTitle = quickFilter === "overdue" ? "Factures en retard" : quickFilter === "pending_quotes" ? "Devis en attente" : "Documents prioritaires";
  const filterCaption = quickFilter === "overdue" ? "Les factures échues avec un solde à suivre." : quickFilter === "pending_quotes" ? "Les brouillons et devis prêts à envoyer." : "Les documents demandant votre attention apparaissent ici.";
  const indicators = [
    { label: "Devis à traiter", value: isLoading ? "…" : String(pendingQuotes.length), caption: "Brouillons et à envoyer", icon: FilePlus2, tone: "bg-[#e3efe7] text-[#1e6051]", onClick: () => setQuickFilter("pending_quotes") },
    { label: "Encours clients", value: formatGnf(receivables?.summary.outstandingTotal ?? 0), caption: `${receivables?.summary.openCount ?? 0} facture(s) impayée(s)`, icon: CircleDollarSign, tone: "bg-[#e4edf7] text-[#31617f]", onClick: () => setLocation("/creances") },
    { label: "En retard", value: formatGnf(receivables?.summary.overdueTotal ?? 0), caption: `${receivables?.summary.overdueCount ?? 0} facture(s) à prioriser`, icon: AlertTriangle, tone: (receivables?.summary.overdueCount ?? 0) > 0 ? "bg-red-100 text-red-700" : "bg-[#f8ebcb] text-[#8c5b13]", alert: (receivables?.summary.overdueCount ?? 0) > 0, onClick: () => setLocation("/creances") },
    { label: "Marge réalisée", value: formatGnf(totalMargin), caption: "Encaissements moins coûts", icon: BarChart3, tone: totalMargin >= 0 ? "bg-[#e3efe7] text-[#1e6051]" : "bg-red-100 text-red-700", alert: totalMargin < 0, onClick: () => setLocation("/couts-chantier") },
  ];

  return <DashboardLayout><div className="mx-auto max-w-7xl space-y-6 lg:space-y-8"><header className="flex flex-col gap-5 border-b border-border pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-primary">Cockpit commercial</p><h1 className="font-editorial mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Bonjour, pilotons l’essentiel.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Une vue d’action de vos documents, créances et marges réalisées pour {LUCEPRES_PUBLIC_PROFILE.displayName}.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setLocation("/factures/nouveau")} className="h-10 rounded-xl border-border bg-card font-bold">Nouvelle facture</Button><Button onClick={() => setLocation("/devis/nouveau")} className="h-10 rounded-xl bg-primary px-4 font-bold text-primary-foreground shadow-lg shadow-primary/15 active:scale-[0.97]"><FilePlus2 className="mr-2 h-4 w-4" />Créer un devis</Button></div></header>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{indicators.map(({ label, value, caption, icon: Icon, tone, alert, onClick }) => <button onClick={onClick} className={`card-shadow rounded-2xl border bg-card p-5 text-left transition-transform duration-150 hover:-translate-y-0.5 ${alert ? "border-red-300 ring-1 ring-red-100" : "border-border"}`} key={label}><div className="flex items-start justify-between"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></div><span className={`font-mono text-xs ${alert ? "font-bold text-red-700" : "text-muted-foreground"}`}>{alert ? "Action requise" : "À jour"}</span></div><p className="mt-5 text-sm font-bold text-muted-foreground">{label}</p><p className={`font-editorial mt-1 text-3xl font-semibold ${alert ? "text-red-700" : ""}`}>{value}</p><p className={`mt-2 text-xs ${alert ? "font-semibold text-red-700" : "text-muted-foreground"}`}>{caption}</p></button>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><article className="card-shadow overflow-hidden rounded-2xl border border-border bg-card"><div className="border-b border-border px-5 py-4 sm:px-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-extrabold">{filterTitle}</p><p className="mt-1 text-xs text-muted-foreground">{filterCaption}</p></div><Button variant="ghost" onClick={() => setLocation(quickFilter === "overdue" ? "/creances" : "/devis")} className="hidden rounded-lg text-xs font-bold text-primary sm:flex">Voir la liste <ArrowUpRight className="ml-1 h-3.5 w-3.5" /></Button></div><div className="mt-4 flex flex-wrap gap-2" role="group" aria-label="Filtres rapides"><FilterButton active={quickFilter === "all"} onClick={() => setQuickFilter("all")}>Toutes les priorités</FilterButton><FilterButton active={quickFilter === "overdue"} tone="danger" onClick={() => setQuickFilter("overdue")}><AlertTriangle className="mr-1.5 h-3.5 w-3.5" />Factures en retard ({overdueInvoices.length})</FilterButton><FilterButton active={quickFilter === "pending_quotes"} onClick={() => setQuickFilter("pending_quotes")}><FilePlus2 className="mr-1.5 h-3.5 w-3.5" />Devis en attente ({pendingQuotes.length})</FilterButton></div></div>{visibleDocuments.length ? <div>{visibleDocuments.map(document => <button onClick={() => setLocation(`/documents/${document.id}`)} key={document.id} className={`flex w-full items-center justify-between gap-3 border-b border-border px-5 py-4 text-left last:border-0 sm:px-6 ${document.isOverdue ? "bg-red-50/70 hover:bg-red-50" : "hover:bg-muted/40"}`}><div className="min-w-0"><p className="font-mono text-xs font-bold text-primary">{document.number}</p><p className="mt-1 truncate text-sm font-extrabold">{document.clientName}</p><p className={`mt-1 text-xs ${document.isOverdue ? "font-bold text-red-700" : "text-muted-foreground"}`}>{document.isOverdue ? "Échéance dépassée · action requise" : document.status.replaceAll("_", " ")}</p></div><div className="shrink-0 text-right"><p className="font-mono text-sm font-bold">{formatGnf(document.total)}</p>{document.kind === "facture" && <p className="mt-1 text-[11px] font-bold text-muted-foreground">Solde : {formatGnf(document.balanceDue)}</p>}</div></button>)}</div> : <div className="flex min-h-[262px] flex-col items-center justify-center px-6 py-10 text-center"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-secondary text-primary"><Send className="h-5 w-5" /></div><h2 className="mt-4 text-sm font-extrabold">Aucun document pour ce filtre</h2><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">Les documents correspondants apparaîtront ici dès qu’ils seront créés ou que leur statut changera.</p></div>}</article>
      <aside className="space-y-4"><section className="relative overflow-hidden rounded-2xl bg-primary p-6 text-primary-foreground shadow-xl shadow-primary/15"><div className="absolute -right-10 -top-10 h-36 w-36 rounded-full border border-white/10" /><div className="relative"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/10"><Sparkles className="h-5 w-5 text-[#f3d48b]" /></div><p className="mt-5 text-xs font-extrabold uppercase tracking-[0.18em] text-[#f3d48b]">Assistant Lucepres</p><h2 className="font-editorial mt-2 text-2xl font-semibold leading-tight">D’un besoin terrain à un devis complet.</h2><Button onClick={() => setLocation("/devis/nouveau?assistant=ia")} className="mt-5 h-10 rounded-xl bg-[#f3d48b] px-4 text-sm font-extrabold text-primary hover:bg-[#f7df9f]"><Bot className="mr-2 h-4 w-4" />Générer un devis</Button></div></section><ActionCard icon={AlertTriangle} title="Prioriser le recouvrement" description={receivables?.summary.overdueCount ? `${receivables.summary.overdueCount} retard(s) requièrent une action.` : "Aucun retard identifié actuellement."} action="Ouvrir les créances" onClick={() => setLocation("/creances")} tone={receivables?.summary.overdueCount ? "danger" : "default"} /><ActionCard icon={BarChart3} title="Contrôler les marges" description={`${profitability.length} chantier(s) suivi(s) par encaissement et coûts réels.`} action="Voir les coûts" onClick={() => setLocation("/couts-chantier")} /><ActionCard icon={CalendarDays} title="Portail client" description="Renseignez l’e-mail client pour lui permettre de consulter ses factures." action="Gérer les clients" onClick={() => setLocation("/clients")} /></aside></section></div></DashboardLayout>;
}

function FilterButton({ active, onClick, tone = "default", children }: { active: boolean; onClick: () => void; tone?: "default" | "danger"; children: React.ReactNode }) { return <button type="button" onClick={onClick} className={`inline-flex h-8 items-center rounded-lg border px-3 text-xs font-bold transition-colors ${active ? tone === "danger" ? "border-red-600 bg-red-600 text-white" : "border-primary bg-primary text-primary-foreground" : tone === "danger" ? "border-red-200 bg-red-50 text-red-700 hover:bg-red-100" : "border-border bg-card text-muted-foreground hover:bg-muted"}`}>{children}</button>; }
function ActionCard({ icon: Icon, title, description, action, onClick, tone = "default" }: { icon: React.ElementType; title: string; description: string; action: string; onClick: () => void; tone?: "default" | "danger" }) { return <section className={`rounded-2xl border bg-card p-4 ${tone === "danger" ? "border-red-200" : "border-border"}`}><div className="flex gap-3"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${tone === "danger" ? "bg-red-100 text-red-700" : "bg-secondary text-primary"}`}><Icon className="h-4 w-4" /></div><div><h2 className="text-sm font-extrabold">{title}</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">{description}</p><button onClick={onClick} className="mt-3 inline-flex items-center text-xs font-extrabold text-primary hover:underline">{action}<ArrowUpRight className="ml-1 h-3.5 w-3.5" /></button></div></div></section>; }
